version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: emlak_crm_backend_container
    restart: unless-stopped
    ports:
      - "5000:5000"
    volumes:
      - ./backend:/app # Hosttaki değişiklikler container'a yansır, app.db burada oluşur
    env_file:
      - ./backend/.env # Backend'in .env dosyasını kullanır (DATABASE_URL SQLite için ayarlı olmalı veya olmamalı)
    networks:
      - emlak-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: emlak_crm_frontend_container
    restart: unless-stopped
    ports:
      - "5173:80" # Nginx 80 portunda çalışacak, biz 5173'e mapliyoruz
    volumes:
      - ./frontend/src:/app/src # Geliştirme için: hosttaki değişiklikler container'a yansır (HMR)
      # Vite için node_modules'ı volume dışında tutmak performans artışı sağlayabilir
      # - /app/node_modules # Bu satırı ekleyerek container içindeki node_modules kullanılır
    # env_file: # Frontend .env dosyası build sırasında VITE_* ile kullanılır
    #   - ./frontend/.env
    depends_on:
      - backend # API çağrıları için backend'in başlamasını bekleyebilir
    networks:
      - emlak-network

networks:
  emlak-network:
    driver: bridge